### ISSUE TITLE
Agregar estilo al selector de año en las gráficas

### ISSUE THREAD

**Issue by elcoruco** [GobiernoFacil/mapadai#1]
<img width="988" alt="screen shot 2016-01-17 at 12 36 07 pm" src="https://cloud.githubusercontent.com/assets/3756555/12379039/eac0c2f4-bd16-11e5-99b5-e0e358221f8e.png">

Aquí el link para la guía de estilo del slider:
http://refreshless.com/nouislider/more/

es Posible que el año que se muestra ahora de lado izquierdo en la sección deinfomex, sea un rango de años (2008 - 2015)

**Comment by elcoruco** [comment]
el branch es: final-graphs

**Comment by hugovom** [comment]
:sleeping: :sleeping: :sleeping:
