### ISSUE TITLE
Agregar botón para descargar datos

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/mapadai#13]

**Comment by hugovom** [comment]
@ArgentinaVelasco me ayudas con ícono?

**Comment by ArgentinaVelasco** [comment]
como lo necesitas, base 64. svg code, o svg tendrás captura de donde va en el diseño?

**Comment by hugovom** [comment]
base64
http://mapadaimx.gobiernofacil.com/infomex.php
<img width="194" alt="screen shot 2016-01-21 at 9 42 18 a m" src="https://cloud.githubusercontent.com/assets/2445854/12485185/46b0cfdc-c023-11e5-9df4-f0382d2066a7.png">
