### ISSUE TITLE
OG  images

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/mapadai#22]

**Comment by ArgentinaVelasco** [comment]
![mapadai_og](https://cloud.githubusercontent.com/assets/2530269/12625860/4488a5a4-c4fb-11e5-8b43-0cc407993b80.png)

**Comment by ArgentinaVelasco** [comment]
![mapadai_og](https://cloud.githubusercontent.com/assets/2530269/12626020/08cb6366-c4fc-11e5-88b7-0b3e36371ff1.png)

**Comment by ArgentinaVelasco** [comment]
asi?

![infomex](https://cloud.githubusercontent.com/assets/2530269/12626095/7b881854-c4fc-11e5-8bb0-87653699361e.png)

**Comment by ArgentinaVelasco** [comment]
![infomex](https://cloud.githubusercontent.com/assets/2530269/12626355/e6e81706-c4fd-11e5-8755-995c35a8c39c.png)
