### ISSUE TITLE
"La liga a la estadística oficial está rota"

### ISSUE THREAD

**Issue by elcoruco** [GobiernoFacil/mapadai#55]
Pues me imagino que en algún lugar, donde se menciona la fuente de los datos del mapa, ya cambió el link. Se me hace que ya lo bajaron jajajaa y dicen que está mal el link. Pero si se puede hacer algo, meter un link que funcione, aunque sea el de derpy-man-hack-and-slash

**Comment by hugovom** [comment]
Pues igual y estaba muerta la plataforma porque sí funciona: http://www.plataformadetransparencia.org.mx/documents/10181/39995/Ejercicio+DAIP+en+México+2008-2014_PEF2016.pdf/5dc80442-4802-4310-8f59-3565a26eb4a9
