### ISSUE TITLE
Cambiarle el nombre a algunos campos del select del mapa

### ISSUE THREAD

**Issue by elcoruco** [GobiernoFacil/mapadai#56]
Aquí me imagino que no quieren que los campos se llamen como la variable interna, y seguro no quieren que se muestren algunos. Se rumora que pepe te dijo cuáles, pero no es info confirmada jajajaa

aquí el truco nomás es ponerle el valor al atributo "value" de cada <option> y poner el texto que quieren dentro del html

**Comment by hugovom** [comment]
- SOLICITUDES	Solicitudes de acceso a la información
- RECURSOS	Recursos de revisión
- INDICE	Índice de recurrencia
- PRESUPUESTO	Presupuesto del órgano garante
- PER CAPITA	Presupuesto asignado al órgano garante per cápita
- RESOLUCION_SOBRESEER	Recursos de revisión sobreseídos
- RESOLUCION_DESECHAR	Recursos de revisión desechados
- RESOLUCION_REVOCAR	Resoluciones que revocan la respuesta del Sujeto Obligado
- RESOLUCIÓN_CONFIRMAR	Resoluciones que confirman la respuesta del Sujeto Obligado
- RESOLUCIÓN_MODIFICAR	Resoluciones que modifican la respuesta del Sujeto Obligado
- RESOLUCIÓN_TRÁMITE	Resoluciones reportadas en trámite (2014)
- RESOLUCIÓN_NO INTERPUESTO	Recursos de revisión no interpuestos
- RESOLUCIÓN_ORDEN ENTREGAR	Resoluciones que ordenan entrega de información
- RESOLUCIÓN_REVOCAR PARCIAL	Resoluciones que revocan parcialmente la respuesta del Sujeto Obligado
- RESOLUCIÓN_REVOCADOS	Resoluciones que revocan la respuesta del Sujeto Obligado
- RESOLUCIÓN_IMPROCEDENTE	Recursos de revisión desechados
- RESOLUCIÓN_DESECHADO	Recursos de revisión desechados
- RESOLUCIÓN_CONFIRMAR RESPUESTA	Resoluciones que confirman la respuesta del Sujeto Obligado

**Comment by elcoruco** [comment]
@hugovom ya quedó esta maroma, pero se ve medio raro. Como que no jala como Ferrari 🚗  (porque títulos largos como la cuaresma jajajaa)

**Comment by hugovom** [comment]
:raised_hands:
